name: Static Site Deploy
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - id: "checkout"
        uses: "actions/checkout@v3"

      - name: "setup node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "18.x"
      
      - name: Cache node modules
          id: cache-npm
          uses: actions/cache@v3
          env:
            cache-name: cache-node-modules
          with:
            # npm cache files are stored in `~/.npm` on Linux/macOS
            path: ~/.npm
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
          name: List the state of node modules
          continue-on-error: true
          run: npm list

      - name: "yarn install"
        run: "yarn install"

      - name: "make src/__generated__"
        run: "mkdir -p src/__generated__"

      - name: "relay build"
        run: "yarn relay:build"

      - name: "rescript build"
        run: "yarn re:build"

      - name: "parcel build"
        run: "yarn parcel:build"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.POOL }}/providers/${{ secrets.PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCT }}"

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "build"
          destination: "${{ secrets.GS_BUCKET }}"
          parent: false
